# Generated by Django 3.0 on 2026-07-11 16:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('transport_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_vehicle', models.CharField(blank=True, max_length=100, null=True)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('place', models.CharField(max_length=100)),
                ('cgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sgst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('igst_amt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
            ],
            options={
                'db_table': 'app_tblbill',
            },
        ),
        migrations.CreateModel(
            name='TblCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('gst', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'app_tblcustomer',
            },
        ),
        migrations.CreateModel(
            name='TblEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_tblemployee',
            },
        ),
        migrations.CreateModel(
            name='TblTax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'app_tbltax',
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('isdeveloper', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='user_pictures/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'app_tbluser',
            },
        ),
        migrations.CreateModel(
            name='TblOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('dc_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_qty', models.IntegerField(default=0)),
                ('shortage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblOrder_customer', to='App.TblCustomer')),
            ],
            options={
                'db_table': 'app_tblorder',
            },
        ),
        migrations.CreateModel(
            name='TblBillitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('hsn', models.CharField(blank=True, max_length=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBillitems_bill', to='App.TblBill')),
            ],
            options={
                'db_table': 'app_tblbillitems',
            },
        ),
        migrations.AddField(
            model_name='tblbill',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBill_customer', to='App.TblCustomer'),
        ),
        migrations.AddField(
            model_name='tblbill',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBill_tax', to='App.TblTax'),
        ),
    ]
