# Generated by Django 3.0 on 2026-07-15 07:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 15, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblbill',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 15, 12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblbill',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tblbill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
