# Generated by Django 4.2.16 on 2026-03-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_tblcustomer_tblemployee_mobile_tblorder_shortage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblorder',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
