# Generated by Django 5.2.6 on 2026-09-08 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_tblbill_id_alter_tblbillitems_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblPayment_customer', to='App.tblcustomer')),
            ],
            options={
                'db_table': 'app_tblpayment',
            },
        ),
    ]
