# Generated by Django 4.2.16 on 2026-04-04 05:54

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tbltax'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblBillitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('hsn', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.BooleanField(default=False)),
                ('qty', models.CharField(max_length=100)),
                ('amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'app_tblbillitems',
            },
        ),
        migrations.CreateModel(
            name='TblBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('transport_mode', models.CharField(max_length=100)),
                ('supply_date', models.DateField(blank=True, null=True)),
                ('transport_vehicle', models.CharField(max_length=100)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBill_customer', to='App.tblcustomer')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBill_tax', to='App.tbltax')),
            ],
            options={
                'db_table': 'app_tblbill',
            },
        ),
    ]
