# Generated by Django 5.2.6 on 2026-09-08 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_tblpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpayment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblPayment_bill', to='App.tblbill'),
        ),
        migrations.AddField(
            model_name='tblpayment',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
