# Generated by Django 4.2.16 on 2026-04-04 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_tblbillitems_tblbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblbill',
            old_name='company_name',
            new_name='customer',
        ),
    ]
