# Generated by Django 5.2.6 on 2026-09-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_tblpayment_bill_tblpayment_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbill',
            name='dc_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBill_dc_number', to='App.tblorder'),
        ),
    ]
