# Generated by Django 4.2.16 on 2026-04-05 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_company_name_tblbill_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblbillitems',
            old_name='description',
            new_name='product',
        ),
        migrations.AddField(
            model_name='tblbillitems',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TblBillitems_bill', to='App.tblbill'),
        ),
        migrations.AlterField(
            model_name='tblbillitems',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tblbillitems',
            name='qty',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tblbillitems',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
