# Generated by Django 5.2.6 on 2026-09-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_tblbill_dc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcustomer',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
