# Generated by Django 4.2.16 on 2026-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_description_tblbillitems_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbillitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
