# Generated by Django 4.2.16 on 2026-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_tblbill_cgst_tblbill_igst_tblbill_place_tblbill_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbill',
            name='cgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tblbill',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='tblbill',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
