# Generated by Django 4.2.16 on 2026-04-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_tblbill_cgst_amt_tblbill_igst_amt_tblbill_sgst_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbill',
            name='total_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
