# Generated by Django 4.2.16 on 2026-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_tblbill_total_gst'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblbill',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
