# Generated by Django 4.2.16 on 2026-04-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_tblbill_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblbill',
            name='cgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tblbill',
            name='igst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tblbill',
            name='sgst_amt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
