# Generated by Django 4.2.16 on 2026-04-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_tblbill_cgst_amt_alter_tblbill_igst_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcustomer',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tblcustomer',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
