# Generated by Django 4.2.23 on 2026-05-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_tblcustomer_cgst_tblcustomer_igst_tblcustomer_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcustomer',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
